// @ts-nocheck
/**
 * `scout-cli profile` — runs three benchmark scenarios with the
 * profiler enabled, collects spans, and writes a Markdown report to
 * docs/superpowers/research/scout-perf-<YYYY-MM-DD>.md.
 *
 * Each scenario runs twice: the first run warms up the JIT and is
 * discarded; the second run is what we report. Both numbers appear
 * in the report so drift between warmup and steady state is visible.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { generate } from '../../../resources/js/workers/scout/engine';
import { resetProfiler, dumpProfile } from '../../../resources/js/workers/scout/scout-profiler';
import { loadContext, DEFAULT_SNAPSHOT_PATH } from '../context';

type Scenario = {
    id: string;
    label: string;
    params: any;
};

const SCENARIOS: Scenario[] = [
    {
        id: 'no-lock',
        label: 'No lock, lvl 8, topN=10',
        params: {
            level: 8,
            topN: 10,
            max5Cost: null,
            minFrontline: 0,
            minDps: 0,
            lockedChampions: [],
            lockedTraits: [],
            excludedChampions: [],
            excludedTraits: [],
            emblems: [],
            seed: 0,
        },
    },
    {
        id: 'tight-lock',
        label: 'Tight lock ShieldTank:6, lvl 10, topN=30',
        params: {
            level: 10,
            topN: 30,
            max5Cost: null,
            minFrontline: 0,
            minDps: 0,
            lockedChampions: [],
            lockedTraits: [{ apiName: 'TFT17_ShieldTank', minUnits: 6 }],
            excludedChampions: [],
            excludedTraits: [],
            emblems: [],
            seed: 0,
        },
    },
    {
        id: 'loose-lock-emblem',
        label: 'Loose ShieldTank:6 + RangedTrait:4 + emblem, lvl 10, topN=30',
        params: {
            level: 10,
            topN: 30,
            max5Cost: null,
            minFrontline: 0,
            minDps: 0,
            lockedChampions: [],
            lockedTraits: [
                { apiName: 'TFT17_ShieldTank', minUnits: 6 },
                { apiName: 'TFT17_RangedTrait', minUnits: 4 },
            ],
            excludedChampions: [],
            excludedTraits: [],
            emblems: [{ apiName: 'TFT17_RangedTrait', count: 1 }],
            seed: 0,
        },
    },
];

function runScenario(scenario: Scenario, ctx: any) {
    resetProfiler();

    const t0 = performance.now();
    generate({
        champions: ctx.champions,
        traits: ctx.traits,
        scoringCtx: ctx.scoringCtx,
        constraints: scenario.params,
        exclusionGroups: ctx.exclusionGroups,
        level: scenario.params.level,
        topN: scenario.params.topN,
        seed: scenario.params.seed,
        stale: ctx.stale,
    });
    const wallMs = performance.now() - t0;

    return { wallMs, spans: dumpProfile() };
}

function formatSpanTable(spans: Array<{ name: string; durationMs: number; count: number }>): string {
    const lines = ['| span | durationMs | count | mean ms |', '| --- | ---: | ---: | ---: |'];

    for (const s of spans) {
        const mean = s.count > 0 ? (s.durationMs / s.count).toFixed(3) : '-';
        lines.push(`| ${s.name} | ${s.durationMs.toFixed(2)} | ${s.count} | ${mean} |`);
    }

    return lines.join('\n');
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export async function runProfile(_argv: string[]): Promise<void> {
    if (process.env.SCOUT_PROFILE !== '1') {
        throw new Error('scout-cli profile: set SCOUT_PROFILE=1 before running so the profiler actually collects spans');
    }

    const ctx = await loadContext({ live: false, snapshotPath: DEFAULT_SNAPSHOT_PATH });
    const date = new Date().toISOString().slice(0, 10);
    const outPath = resolve(process.cwd(), `docs/superpowers/research/scout-perf-${date}.md`);

    mkdirSync(dirname(outPath), { recursive: true });

    const sections: string[] = [
        `# Scout performance profile — ${date}`,
        '',
        '> Generated by `scout-cli profile`. Each scenario runs twice;',
        '> the second run is the one you care about (first warms up JIT).',
        '',
    ];

    for (const scenario of SCENARIOS) {
        sections.push(`## ${scenario.label}`);
        sections.push('');

        const warm = runScenario(scenario, ctx);
        sections.push(`**Warmup wall time:** ${warm.wallMs.toFixed(1)} ms`);
        sections.push('');

        const measured = runScenario(scenario, ctx);
        sections.push(`**Measured wall time:** ${measured.wallMs.toFixed(1)} ms`);
        sections.push('');
        sections.push('### Top spans (measured run, sorted by total durationMs)');
        sections.push('');
        sections.push(formatSpanTable(measured.spans.slice(0, 25)));
        sections.push('');
    }

    writeFileSync(outPath, sections.join('\n'), 'utf8');

    console.log(`profile report written to ${outPath}`);
}
